name: WinCopy
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  win32-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.15.2]
        qt_target: [desktop]
        qt_arch: [win64_msvc2019_64, win32_msvc2019]
        include:
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
            mingw_arch: MINGW64 
          - qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019
            mingw_arch: MINGW32
    env:
      targetName: WinCopy
      
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
                    
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install: zip curl
          
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      
      - name: Set up jom
        shell: cmd
        run: |
          mkdir jom
          cd jom
          curl.exe -o jom.zip -L https://download.qt.io/official_releases/jom/jom_1_1_3.zip
          7z.exe x jom.zip
          cd ..
          
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%PATH%;%CD%\jom
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ..\${{ env.targetName }}.pro
          jom -j %NUMBER_OF_PROCESSORS%
          cd ..
          
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\Release\WinCopy.exe
          name: WinCopy-${{ matrix.qt_arch }}
          
  win32-clang-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.15.2]
        qt_target: [desktop]
        qt_arch: [win64_msvc2019_64, win32_msvc2019]
        include:
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
            mingw_arch: MINGW64 
            clang_link: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/LLVM-11.0.0-win64.exe
          - qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019
            mingw_arch: MINGW32
            clang_link: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/LLVM-11.0.0-win32.exe
    env:
      targetName: WinCopy
      
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
                    
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install: zip curl
          
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          
      - name: Set up clang for Windows
        shell: cmd
        run: |
          mkdir llvm
          cd llvm
          curl.exe -o LLVM.exe -L ${{ matrix.clang_link }}
          7z.exe x LLVM.exe
          cd ..
      
      - name: Set up jom
        shell: cmd
        run: |
          mkdir jom
          cd jom
          curl.exe -o jom.zip -L https://download.qt.io/official_releases/jom/jom_1_1_3.zip
          7z.exe x jom.zip
          cd ..
          
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%PATH%;%CD%\llvm\bin;%CD%\jom
          mkdir build
          cd build
          qmake -r -spec win32-clang-msvc CONFIG+=release CONFIG+=qtquickcompiler ..\${{ env.targetName }}.pro
          jom -j %NUMBER_OF_PROCESSORS%
          cd ..
          
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\Release\WinCopy.exe
          name: WinCopy-clang-${{ matrix.qt_arch }}
          
  win32-mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [mingw64_qt5-gcc, mingw32_qt5-gcc, mingw64_qt5-static-gcc, mingw32_qt5-static-gcc, mingw64_qt5-clang, mingw32_qt5-clang]
        include:
          - qt_arch: mingw64_qt5-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: mingw32_qt5-gcc
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: mingw64_qt5-static-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5-static
            qmake: /mingw64/qt5-static/bin/qmake.exe
            windeployqt: ls.exe
          - qt_arch: mingw32_qt5-static-gcc
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5-static
            qmake: /mingw32/qt5-static/bin/qmake.exe
            windeployqt: ls.exe
          - qt_arch: mingw64_qt5-clang
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: clang
            mkspec: win32-clang-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: mingw32_qt5-clang
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: clang
            mkspec: win32-clang-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
    env:
      targetName: WinCopy
      
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install:  ${{ matrix.mingw_prefix }}-${{ matrix.toolchains }} ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-${{ matrix.qt_build }} ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          submodules: true

      - name: qmake
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          ${{ matrix.qmake }} -r -spec ${{ matrix.mkspec }} CONFIG+=release CONFIG+=qtquickcompiler ..
          cd ..

      - name: mingw32-make
        shell: msys2 {0}
        run: |
          cd build
          mingw32-make.exe -j $NUMBER_OF_PROCESSORS
          cd ..

      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\Release\WinCopy.exe
          name: WinCopy-${{ matrix.qt_arch }}
